[package]
name = "aoc-23"
version = "1.0.0"
publish = false
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2021"

[dependencies]
itertools = "0.12"
once_cell = "1"
regex = "1.10"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day1.rs"
